### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by adrobisch** [prometheus-community/elasticsearch_exporter#305]
Hi, thanks for the exporter, its super useful for us!

We noticed that there has not been a release in a while, many changes were merge into master since v1.1.0 (we are interested in https://github.com/justwatchcom/elasticsearch_exporter/pull/277 which is already 4 months old). 

Are you planning to cut a new release in near the future (or maybe just pushing a snapshot docker image to try out the current master)?

**Comment by adrobisch** [comment]
I published a snapshot on my own, maybe its useful to others: https://hub.docker.com/repository/docker/adrobisch/elasticsearch_exporter

**Comment by bartjolenovation** [comment]
I see #277 has been included in 1.2.0: https://github.com/prometheus-community/elasticsearch_exporter/blob/master/CHANGELOG.md#120--2021-06-10 so I think this issue can be closed. Tnx for the snapshot!
