### ISSUE TITLE
failed to fetch and decode snapshot stats" err:"json: cannot unmarshal object into Go struct field .settings of type string"

### ISSUE THREAD

**Issue by bydeath** [prometheus-community/elasticsearch_exporter#415]
it failed to scrape snapshots stats

warn log:
snapshots.go:265 msg "failed to fetch and decode snapshot stats" err:"json: cannot unmarshal object into Go struct field .settings of type string"

I am using the exporter of latest version V1.1.0, elasticsearch version is 7.9.2.

**Comment by bydeath** [comment]
To reproduce the issue, install the elasticsearch plugin repository-hdfs https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-hdfs-config.html#repository-hdfs-config
``` and create a hdfs type repository like this. To reproduce, `conf` field should be set. 
PUT _snapshot/my_hdfs_repository
{
  "type": "hdfs",
  "settings": {
    "uri": "hdfs://namenode:8020/",
    "path": "elasticsearch/repositories/my_hdfs_repository",
    "conf.dfs.client.read.shortcircuit": "true"
  }
}
```

**Comment by JohnMops** [comment]
Any news on this one ?

**Comment by sysadmind** [comment]
#442 addressed this issue.

**Comment by autokilla47** [comment]
+1
