### ISSUE TITLE
quay.io image pull is unauthorized

### ISSUE THREAD

**Issue by PeterGrace** [prometheus-community/elasticsearch_exporter#437]
The readme indicates that I should be able to `docker pull quay.io/prometheuscommunity/elasticsearch_exporter:1.1.0` -- however, I cannot, because I get an "Unauthorized."  When I go to the quay.io page for elasticsearch_exporter, it also shows a 403 there, which is different from other public projects.

I think there might be an issue with the config in quay?

**Comment by roidelapluie** [comment]
Can you try 1.2.0, and if it works, would you mind sending  a PR to update the documentation? Thanks!

**Comment by PeterGrace** [comment]
@roidelapluie Unfortunately that does not work either:
```
  $   docker pull quay.io/prometheuscommunity/elasticsearch_exporter:1.2.0
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

**Comment by roidelapluie** [comment]
The tags should be :v1.2.0

**Comment by PeterGrace** [comment]
```
  $   docker pull quay.io/prometheuscommunity/elasticsearch_exporter:v1.2.0
Error response from daemon: unauthorized: access to the requested resource is not authorized
  $   docker pull quay.io/prometheuscommunity/elasticsearch_exporter:v1.1.0
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

additionally https://quay.io/prometheuscommunity/elasticsearch_exporter is a 403.

**Comment by roidelapluie** [comment]
```
docker pull quay.io/prometheuscommunity/elasticsearch-exporter:v1.2.0
```

**Comment by PeterGrace** [comment]
looks like PR #435 updates the docs as you mention, I will retest when at my console next.

**Comment by PeterGrace** [comment]
Yes, can confirm that the hyphen works as expected.  Closing this issue, thanks for the help.
