### ISSUE TITLE
Not able to use API Keys from Elastic Cloud 

### ISSUE THREAD

**Issue by TrafeX** [prometheus-community/elasticsearch_exporter#454]
We're running Elasticsearch on Elastic Cloud and they don't allow Basic Auth as authentication method.
You can only use [API Keys](https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html).

Unfortunately I can't find a way to use this Elasticsearch exporter with API Keys. I tried to include the id and key as username and password in the URI in different ways, but Elasticsearch doesn't accept that.

Is there a way to use an API key as authentication method?

**Comment by roko99** [comment]
Hello guys, sorry for writing into closed issue. 
But I want to ask @TrafeX - did you mean [managed elasticsearch](https://www.elastic.co/cloud/) by "Elastic Cloud"? I couldn't discover the endpoint, which should expose elastic metrics. Could you please give me an example or a link to elastic cloud docs (may be I've missed it)?
