### ISSUE TITLE
Fails to export lots of metrics in ES 7.14.0

### ISSUE THREAD

**Issue by KnechtionsCoding** [prometheus-community/elasticsearch_exporter#464]
After upgrading ES to 7.14.0 Exporter only exports some metrics properly.

Cluster status, Running nodes, data nodes, pending tasks, active shards, primary shards, etc. Work.

Document metrics, system metrics (JVM, Mem, CPU, etc) don't work.
<img width="1703" alt="Screen Shot 2021-08-06 at 10 10 13 AM" src="https://user-images.githubusercontent.com/6039922/128523168-ea2de6a6-3781-4c44-a49d-5ec5b6cee157.png">

Example screenshots below. 
<img width="1717" alt="Screen Shot 2021-08-06 at 10 09 58 AM" src="https://user-images.githubusercontent.com/6039922/128523163-ede19692-80d4-4bc5-b99c-64a7728f221e.png">
<img width="1700" alt="Screen Shot 2021-08-06 at 10 10 05 AM" src="https://user-images.githubusercontent.com/6039922/128523165-ad904489-e0f0-4b94-898f-9f37cc62d90d.png">

The same is true when run via prometheus
<img width="2551" alt="Screen Shot 2021-08-06 at 10 22 15 AM" src="https://user-images.githubusercontent.com/6039922/128524740-a7777973-52ab-4ebd-baf1-053d4ea57030.png">

I didn't see anything in the release notes that would tell me they change their metrics output/endpoints, etc.

**Comment by sysadmind** [comment]
I assume your screenshot has redacted the cluster name. Is that correct? 

Can you post log output from the elasticsearch_exporter?

**Comment by KnechtionsCoding** [comment]
That is correct. I redacted cluster name.

```
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T13:30:41.235729885Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T13:35:41.239253286Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T13:40:41.239228289Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T13:45:41.239225291Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T13:50:41.239252661Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T13:55:41.239271642Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T14:00:41.239526501Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T14:05:41.239205902Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T14:10:41.239212037Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T14:15:41.239502873Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T14:20:41.239237569Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
elastic-exporter-7bcf4f5486-vfw8z elastic-exporter level=info ts=2021-08-09T14:25:41.239217891Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
```

**Comment by frittentheke** [comment]
Maybe this is related to https://github.com/prometheus-community/elasticsearch_exporter/issues/429

**Comment by KnechtionsCoding** [comment]
I'll try it out @frittentheke and let you know if that works

**Comment by KnechtionsCoding** [comment]
It was actually a service monitor problem. If I went into the cluster and curled the service directly, it worked, so then solved the service monitor and should be good to go.
