### ISSUE TITLE
Elasticsearch shards per node metric missing

### ISSUE THREAD

**Issue by manuelbs88** [prometheus-community/elasticsearch_exporter#484]
Hello team,

First of all, very sorry in case this already exist and I'm not been successful in my findings...

I would like to monitor the ratio between the nº of nodes, the heap memory available and the nº of shards assigned per node.

Why?

To avoid oversharding situations, the recommendation is to be HEAP_MEM x 20 => Total shards per node to be in a 'balanced' state. In other way, oversharding states provokes bad performance within the cluster.

So that, I have not been able to find any metric to retrieve the number of shards per node.

We have shards metrics at cluster level:
elasticsearch_cluster_health_active_primary_shards
elasticsearch_cluster_health_active_shards
elasticsearch_cluster_health_delayed_unassigned_shards
elasticsearch_cluster_health_initializing_shards
...
But they all have 'cluster' dimension.

Is there any way to retrieve from the exporter the number of shards per node?
The only metric related to shards and nodes, is the "elasticsearch_indices_shards_docs" that is not what I need at all, since this is the number of documents per shard, per index and per node.

Is there any metric we can use for this? 
In case it is not, which should be the process to request it as a new feature?

Thanks in advance guys.
Regards,
M

**Comment by rlapond** [comment]
bump, I'm also interested in this metric.

**Comment by manuelbs88** [comment]
up. Does anyone know if this is possible to get extracted by any other way?

**Comment by rubensselvakumar** [comment]
I am also waiting for this metric :) 

I tried a work around(might be wrong! as well), it did get the value but the value but did not match the count of elasticsearch_cluster_health_active_primary_shards

count(elasticsearch_indices_shards_store_size_in_bytes{instance=~"$instance",cluster=~"$cluster"}) by (node)
count(elasticsearch_indices_shards_store_size_in_bytes{instance=~"$instance",cluster=~"$cluster",primary="true"}) by (node)
count(elasticsearch_indices_shards_store_size_in_bytes{instance=~"$instance",cluster=~"$cluster",primary="false"}) by (node)

FYI : In the output the label for node name(name) is replaced with node_id, there is an issue already raised for adding node name label for this shards metric

**Comment by korcadr** [comment]
bump, I'm also interested in this metric.

**Comment by artyomovs** [comment]
In the same room :)

**Comment by BaptistePiron** [comment]
> 

Also interested in the metric.
I did the same query than yours (with elasticsearch_indices_shards_docs instead of elasticsearch_indices_shards_store_size_in_bytes) and I also have results slightly different of what elasticsearch reports. I have around 50 less shards with the query.

**Comment by BaptistePiron** [comment]
> I am also waiting for this metric :)
> 
> I tried a work around(might be wrong! as well), it did get the value but the value did not match the count of elasticsearch_cluster_health_active_shards count(elasticsearch_indices_shards_store_size_in_bytes{instance="$instance",cluster="$cluster"}) by (node)
> 
> These two very closely matches count of elasticsearch_cluster_health_active_primary_shards, (< 4 shards) count(elasticsearch_indices_shards_store_size_in_bytes{instance="$instance",cluster="$cluster",primary="true"}) by (node) count(elasticsearch_indices_shards_store_size_in_bytes{instance="$instance",cluster="$cluster",primary="false"}) by (node)
> 
> FYI : In the output label, node name(name) is replaced with node_id, there is an issue[#484](https://github.com/prometheus-community/elasticsearch_exporter/issues/486) already in place for adding node name label for this shards metric


Also interested in the metric.
I did the same query than yours (with elasticsearch_indices_shards_docs instead of elasticsearch_indices_shards_store_size_in_bytes) and I also have results slightly different of what elasticsearch reports. I have around 50 less shards with the query.

**Comment by anjaweigel-tng** [comment]
I am also very interested in this metric.

@BaptistePiron, @rubensselvakumar I will also be using your workaround in the meantime. The reason why this number differs from the total is that for elasticsearch_indices_shards_store_size_in_bytes and elasticsearch_indices_shards_docs, only non-internal indices are taken into consideration.

**Comment by anjaweigel-tng** [comment]
Update: This seems to be fixed by: https://github.com/prometheus-community/elasticsearch_exporter/pull/535
Thanks guys! :)

**Comment by lllsJllsJ** [comment]
@anjaweigel-tng , 

Do you know how can I query that metric in current release? it seems not apear in the docs.

**Comment by manuelbs88** [comment]
Hello @lllsJllsJ try with this one:
elasticsearch_node_shards_total

Thanks a lot guys! Specially the ones implementing https://github.com/prometheus-community/elasticsearch_exporter/pull/535 !
