### ISSUE TITLE
Hope to support cgroup cpu usage

### ISSUE THREAD

**Issue by zcola** [prometheus-community/elasticsearch_exporter#488]
We restrict cpu through docker, in kibana only cgroup has reference significance
![image](https://user-images.githubusercontent.com/3234989/138670646-c02c2ebd-4a7e-4939-aa3d-dbb14ec53884.png)

**Comment by SuperQ** [comment]
This is out of scope for this exporter. You probably want [cAdvisor](https://github.com/google/cadvisor).
