### ISSUE TITLE
elasticsearch_indices_docs for small clusters

### ISSUE THREAD

**Issue by LukoJy3D** [prometheus-community/elasticsearch_exporter#512]
Hello, looking for some insights here.

I use `increase(elasticsearch_indices_docs{es_data_node="true"}[10m]) < 1` expression to check if my ES nodes are receiving new docs and it works great when checking big clusters who constantly getting data, however when using same expression for smaller clusters I constantly see that it shows that no new docs are being fetched although when taking a look inside cluster I can see that indices are growing in size.

Does someone have suggestions what to use as alternative or this is something to look at ES itself?

**Comment by sysadmind** [comment]
What are you looking at inside the cluster to know that it is growing in size? The `elasticsearch_indices_docs` metric looks at the number of docs in all indices across the node.

**Comment by LukoJy3D** [comment]
simply by checking with `curl http://localhost:9200/_cat/indices?v` and I see that shard size is increasing, however I came across info that on ES 7.0 there is no refresh until shard is in any search query https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_skipped_background_refresh_on_search_idle_shards. So this might be causing issues for doc count not updating as these clusters are not intensively used. Will be checking this after Holidays and will update issue accordingly. Thanks for taking time to respond 🚀

**Comment by LukoJy3D** [comment]
We tried introducing `refresh_interval = 60s` that solved our problem - index document count was getting refreshed continuously, however that resulted in higher load on cluster nodes, so we decided not to go this way. Instead we started monitoring `elasticsearch_indices_merges_docs_total` which more or less will let us know if cluster stops receiving traffic
