### ISSUE TITLE
 elasticsearch_exporter for es7.16.3

### ISSUE THREAD

**Issue by Csoulsi** [prometheus-community/elasticsearch_exporter#516]
log:
level=warn ts=2022-01-04T03:06:03.280206817Z caller=nodes.go:1851 msg="failed to fetch and decode node stats" err="json: cannot unmarshal array into Go struct field NodeStatsNodeResponse.http of type int"

start cmd:
 /work/esexporter_new/elasticsearch_exporter --es.uri http://elastic:afafdadfafdafadfa@xxx.es.domain.com:9240 --es.all --web.listen-address=:9150 --es.indices --es.indices_settings --es.cluster_settings --es.shards --es.snapshots --log.output=stdout

**Comment by sysadmind** [comment]
What version of the exporter are you running? I believe this has been fixed already. 1.3.0 is the most recent.

**Comment by Csoulsi** [comment]
Thanks
