### ISSUE TITLE
Format stdout logs

### ISSUE THREAD

**Issue by mitct23** [prometheus-community/elasticsearch_exporter#549]
Hi,
Currently, Elasticsearch exporter is printing stdout logs like below
`{"caller":"clusterinfo.go:200","level":"info","msg":"triggering initial cluster info call","ts":"2022-03-02T09:53:03.351423632Z"}
{"caller":"clusterinfo.go:169","level":"info","msg":"providing consumers with updated cluster info label","ts":"2022-03-02T09:53:03.352844512Z"}
{"caller":"main.go:154","level":"info","msg":"initial cluster info call timed out","ts":"2022-03-02T09:53:13.359381587Z"}
{"addr":":9114","caller":"main.go:189","level":"info","msg":"starting elasticsearch_exporter","ts":"2022-03-02T09:53:13.359865623Z"}`
Is there any provision to format this log like printing the key&value pair that we need ?

**Comment by sysadmind** [comment]
This exporter is using the `github.com/go-kit/log` package for logging. The options in that package are json or logfmt (which is the default)
