### ISSUE TITLE
What ES versions are supported?

### ISSUE THREAD

**Issue by jsirianni** [prometheus-community/elasticsearch_exporter#559]
Are the supported ES versions documented anywhere? Also, was Elasticsearch 1.x ever supported? If so, is it still supported / when was support dropped?

**Comment by sysadmind** [comment]
I'm not sure if 1.x was every supported, but we try to maintain support for the currently supported versions of elasticsearch. Currently that is 7.X and 8.X. We do not intentionally break compatibility with older versions, however we do not go out of our way to test older versions either. You could try and run it against 1.x, but there is no guarantee. We would consider PRs that support older versions so long as they do not effect current versions.
