### ISSUE TITLE
Tutorial on how to deploy this exporter in Docker?

### ISSUE THREAD

**Issue by MFurqanHashmi** [prometheus-community/elasticsearch_exporter#594]
[This comment](https://github.com/prometheus-community/elasticsearch_exporter/issues/56#issuecomment-312448683) in one of the closed issues mentioned that there are some documentation and examples on how to deploy this exporter in Docker. I haven't been able to find them via the Readme or the Promethus Docs page.

Could someone point me in the right direction?

**Comment by sysadmind** [comment]
https://github.com/prometheus-community/elasticsearch_exporter#docker
