### ISSUE TITLE
Node.go json: cannot unmarshal array into Go struct field NodeStatsNodeResponse.http of type int

### ISSUE THREAD

**Issue by med502** [prometheus-community/elasticsearch_exporter#600]
Exporter is unable to fetch node specific metrics due to json unmarshall error.
I run elasticsearch cluster on kubernetes setup, exporter is able to fetch only part of the metrics about overall health of the cluster and shards/indices status, due to node module issue node specific metrics are not being fetched.
Is anyone able to help with that bug?

Logs below
level=info ts=2022-07-07T10:13:01.545639112Z caller=clusterinfo.go:200 msg="triggering initial cluster info call"
level=info ts=2022-07-07T10:13:01.545694805Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2022-07-07T10:13:01.632335065Z caller=main.go:148 msg="started cluster info retriever" interval=5m0s
level=info ts=2022-07-07T10:13:01.632522256Z caller=main.go:188 msg="starting elasticsearch_exporter" addr=:9108
level=warn ts=2022-07-07T10:14:20.745946691Z caller=nodes.go:1851 msg="failed to fetch and decode node stats" err="json: cannot unmarshal array into Go struct field NodeStatsNodeResponse.http of type int"
level=warn ts=2022-07-07T10:15:03.847287632Z caller=nodes.go:1851 msg="failed to fetch and decode node stats" err="json: cannot unmarshal array into Go struct field NodeStatsNodeResponse.http of type int"
level=warn ts=2022-07-07T10:16:03.828184921Z caller=nodes.go:1851 msg="failed to fetch and decode node stats" err="json: cannot unmarshal array into Go struct field NodeStatsNodeResponse.http of type int"
level=warn ts=2022-07-07T10:17:03.823032492Z caller=nodes.go:1851 msg="failed to fetch and decode node stats" err="json: cannot unmarshal array into Go struct field NodeStatsNodeResponse.http of type int"
level=info ts=2022-07-07T10:18:01.545819789Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"

**Comment by med502** [comment]
elasticsearch version 7.16.3

**Comment by zengxilong** [comment]
What's your elasticsearch_exporter version? You may need to increase your elasticsearch_exporter version to above 1.21. The type of NodeStatsNodeResponse.http has changed from map[string]int to map[string]interface{}.

**Comment by med502** [comment]
I'm using exporter with version 1.3.0 the latest version from latest helm chart

**Comment by med502** [comment]
> What's your elasticsearch_exporter version? You may need to increase your elasticsearch_exporter version to above 1.21. The type of NodeStatsNodeResponse.http has changed from map[string]int to map[string]interface{}.

I'm using exporter with version 1.3.0 the latest version from latest helm chart

**Comment by med502** [comment]
Issue resolved by replacing image with newest from this repo, Helm Chart contains buggy image
quay.io/prometheuscommunity/elasticsearch-exporter:latest
