### ISSUE TITLE
--es.slm is not working 

### ISSUE THREAD

**Issue by prabhakartalari** [prometheus-community/elasticsearch_exporter#601]
Team,

We were trying get the metrics of elastic snapshots with --es.slm but it is not working and getting following error 

elasticsearch_exporter: error: unknown long flag '-e', try --help

Could some one help us is it working and am using es exporter version 1.3.0 which is latest one

ES Version is : 7.17.5

Thanks,

**Comment by zengxilong** [comment]
--es.slm command is not supported in version 1.30, you can use the command in the master branch.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/46586653/178639337-75ecfc2d-2292-423a-a33b-0a03bc05ca80.png">

**Comment by sysadmind** [comment]
1.4.0 includes the SLM metrics. 
https://github.com/prometheus-community/elasticsearch_exporter/releases/tag/v1.4.0
