### ISSUE TITLE
Adding -e value to docker run command does not have any effect

### ISSUE THREAD

**Issue by stobbe99** [prometheus-community/elasticsearch_exporter#608]
Hello,

I try to start with below,,

docker run --rm  -e "--es.uri=https://elastic:xvOlXhTfP97lgIYGJ9SR@localhost:9200"  -p 9114:9114 quay.io/prometheuscommunity/elasticsearch-exporter:latest

but it looks like no result?level=info ts=2022-07-28T10:16:26.0044181Z caller=clusterinfo.go:214 msg="triggering initial cluster info call"
level=info ts=2022-07-28T10:16:26.0047542Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
level=error ts=2022-07-28T10:16:26.0102599Z caller=clusterinfo.go:267 msg="failed to get cluster info" err="Get \"http://localhost:9200/\": dial tcp 127.0.0.1:9200: connect: connection refused"
level=error ts=2022-07-28T10:16:26.0107353Z caller=clusterinfo.go:188 msg="failed to retrieve cluster info from ES" err="Get \"http://localhost:9200/\": dial tcp 127.0.0.1:9200: connect: connection refused"
level=info ts=2022-07-28T10:16:36.0089812Z caller=main.go:231 msg="initial cluster info call timed out"
level=info ts=2022-07-28T10:16:36.0092637Z caller=main.go:266 msg="starting elasticsearch_exporter" addr=:9114

What am I doing wrong?

KR Henk

**Comment by sysadmind** [comment]
-e is for environment variables. --es.uri is a command line flag. 

Change it to be `docker run --rm -p 9114:9114 quay.io/prometheuscommunity/elasticsearch-exporter:latest --es.uri=https://.....`

**Comment by stobbe99** [comment]
Rookie mistake... Thanks for your help, it works like a charm,

KR Henk
