### ISSUE TITLE
AWS Opensearch authentication failure

### ISSUE THREAD

**Issue by symmetriac** [prometheus-community/elasticsearch_exporter#624]
We have AWS Opensearch cluster 1.3 and elasticsearch exporter running in EKS cluster with irsa role.
In Opensearch we have role with needed permissions and mapping for the irsa role.
Elasticsearch exporter running with `--aws-region` option so it uses the AWS_WEB_IDENTITY_TOKEN_FILE for authentication.

It's all works well and we see a metrics in grafana and no errors in exporter logs, but after 1 hour it starts to show 403 error code in logs.
In Opensearch audit logs for the exporter requests we can see that it doesn't use irsa role arn anymore:
```
"audit_request_effective_user": "<NONE>"
```

After exporter pod restarting errors are gone and metrics available again, but the issue reoccurs after 1 hour.

**Comment by symmetriac** [comment]
UPD: If I run exporter on ec2 with IAM role attached, it works as expected.

**Comment by sysadmind** [comment]
@symmetriac Is your problem resolved? I'm not sure I understand the original problem, but your last comment makes it sound like the problem has been resolved. If not, please re-open with some more context if possible.
