### ISSUE TITLE
Is it safe to pass credentials on the URL?

### ISSUE THREAD

**Issue by hedeesaa** [prometheus-community/elasticsearch_exporter#646]
I saw that credentials are being passed through URL `HTTP://user:pass@es:port`
Is it safe? we are passing credentials in clear text is doesn't seem safe
Is there any other way to do the authentication?

**Comment by sysadmind** [comment]
There are two environment variables available for passing username and password outside of command line arguments

https://github.com/prometheus-community/elasticsearch_exporter#elasticsearch-7x-security-privileges
