### ISSUE TITLE
err="invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by vergusocloud** [prometheus-community/elasticsearch_exporter#665]
Our pod wouldn't start because of this error using the latest image (1.5.0), can someone advise and help with the workaround?

Error log:
`level=error  caller=clusterinfo.go:188 msg="failed to retrieve cluster info from ES" err="invalid character '<' looking for beginning of value"`

----------------------------------------------
command = ["/bin/elasticsearch_exporter"]
args = [
  "--es.uri=https://url",
  "--es.all",
  "--es.indices",
  "--es.indices_settings",
  "--es.shards",
  "--es.snapshots",
  "--es.data_stream",
  "--es.timeout=30s",
  "--web.listen-address=8080",
]

**Comment by sysadmind** [comment]
This suggests that the URL is wrong. There is a `<` as the first character of the response from the cluster info endpoint which means that the endpoint did not respond with JSON.
