### ISSUE TITLE
Retrieving ILM metrics - pod fails

### ISSUE THREAD

**Issue by m4sb5r** [prometheus-community/elasticsearch_exporter#677]
I have tried to use ILM metrics feature added in PR #513. This setup is running on kubernetes and I have the pod running with the flag:
`    Command:
      elasticsearch_exporter
      --es.ilm`
When I start the pod it fails with the following error message:

`panic: inconsistent label cardinality: expected 3 label values but got 1 in []string{"STOPPED"}goroutine 380 [running]:github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/value.go:107github.com/prometheus-community/elasticsearch_exporter/collector.(*IlmStatusCollector).Collect(0xc000305180, 0xc000590120)        /app/collector/ilm_status.go:159 +0x3c8github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:446 +0x10dcreated by github.com/prometheus/client_golang/prometheus.(*Registry).Gather        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:538 +0xb0c`

The pod image being used is quay.io/prometheuscommunity/elasticsearch-exporter:master. I wouldn't know where to start troubleshooting this. Sorry if this issue doesn't meet the standard in some way, since this is the first time I have ever opened an issue. Let me know how if this is the case and I will try my best to improve.

**Comment by sysadmind** [comment]
Thanks for tracking that down @tortuegenialez. That made understanding the fix rather trivial. PR is open to resolve.
