### ISSUE TITLE
Timeline for a new release?

### ISSUE THREAD

**Issue by gsmith-sas** [prometheus-community/elasticsearch_exporter#706]
I see that a good bit of work has been done since the 1.5.0 release became available 8 months ago (28JUL23).  Any timelines for when the next official release will be available?  And, will it be a major release (2.0), minor (1.6) or patch release (1.5.1)?  We'd like to pick up the various security patches but also feel more comfortable with official releases rather than just grabbing the main/master branch.  Thanks!

**Comment by dancristiancecoi** [comment]
Curious about this as well.

**Comment by infa-kparida** [comment]
We are also looking for the next release

**Comment by sysadmind** [comment]
1.6.0 has been released
