### ISSUE TITLE
how to use elastic user encrypted password in elasticsearch exporter service file

### ISSUE THREAD

**Issue by soniekta** [prometheus-community/elasticsearch_exporter#725]
Hi 

I want to use encrypted password in --es-ul in the elastic search-exporter service file 

currently, I am using plain text 

OS- Linux
elasticsearch_exporter version-1.3.0
elaticsearch version-7.17

**Comment by mingregister** [comment]
Based on my understanding of elasticsearch_exporter, this is not achievable.

**Comment by soniekta** [comment]
ok thanks @mingregister
