### ISSUE TITLE
how to correctly pass login/password through ES_USERNAME/ES_PASSWORD variables

### ISSUE THREAD

**Issue by aleksss55** [prometheus-community/elasticsearch_exporter#742]
Hello. Could you please help me with the following issue? I set up elasticsearch exporter, elasticsearch cluster has authentication configured, so I pass ES_USERNAME and ES_PASSWORD environment variables in request URI when launching exporter: ./elasticsearch_exporter --es.uri=https://$ES_USERNAME:$ES_PASSWORD@myhost:9200, but at startup I get an authentication error 401. At the same time, if I directly pass the login/password to the request URI ./elasticsearch_exporter --es.uri=https://myuser:mypassword@myhost:9200, then everything works correctly, but this method is insecure and login/password are displayed in the output of ps aux and systemctl status. How to correctly pass these variables? The output echo $ES_USERNAME and echo $ES_PASSWORD displays the correct value

**Comment by EvgeniiAl** [comment]
You need to override the container's entrypoint and to `/bin/sh`  and the full command will look like `/bin/sh -c "/elasticsearch_exporter --es.uri=https://$ES_USERNAME:$ES_PASSWORD@myhost:9200" `

**Comment by sysadmind** [comment]
If you are setting the environment variables, leave it totally out of the --es.uri. 
I.E. 
```
export ES_USERNAME=myusername
export ES_PASSWORD='mypa$$w0rd'
./elasticsearch_exporter --es.uri="https://myhost:9200"
```
