### ISSUE TITLE
Need Elastic search exporter rpm package for 1.6.0 version

### ISSUE THREAD

**Issue by mukularora-sf** [prometheus-community/elasticsearch_exporter#753]
Hi, How can I get rpm package for 1.6.0 version? How it gets pushed to prometheus_rpm here - https://packagecloud.io/app/prometheus-rpm/release?

**Comment by mukularora-sf** [comment]
@sysadmind can you help here?

**Comment by sysadmind** [comment]
We do not publish official RPMs of the exporter. You would have to build your own RPMs.
