### ISSUE TITLE
Not getting "elasticsearch_node_shards_total" in 1.6.0 release

### ISSUE THREAD

**Issue by mukularora-sf** [prometheus-community/elasticsearch_exporter#758]
hi @avee137 I tried deploying the latest version 1.6.0 of elasticsearch_exporter which has your PR [#535](https://github.com/prometheus-community/elasticsearch_exporter/pull/535/files). 

I am able to get "elasticsearch_node_shards_json_parse_failures" but not getting "elasticsearch_node_shards_total". Please let me know if I am missing anything.

**Comment by mukularora-sf** [comment]
In elasticsearch exporter options, I have enabled --es.indices and --es.shards also.

**Comment by mukularora-sf** [comment]
Issue was related to permission, fixed it by passing username and password in es.uri

**Comment by kvadaliyasalesforce** [comment]
can we have indices information also embedded in this metric?
