### ISSUE TITLE
Wrong metric type for index document counts ?

### ISSUE THREAD

**Issue by kuseman** [prometheus-community/elasticsearch_exporter#785]
Is there any special reason these metrics are `gauge`'s and not a `counter`'s ?

https://github.com/prometheus-community/elasticsearch_exporter/blob/master/README.md?plain=1#L143-L147

Isn't these values simple counts only?
![image](https://github.com/prometheus-community/elasticsearch_exporter/assets/326507/b5765a88-cca7-4123-9925-e0eeef3e1e9c)

**Comment by sysadmind** [comment]
No special reason. They should be converted to a counter long term. As far as I am aware, there is no difference to prometheus itself.
