### ISSUE TITLE
elasticsearch_exporter error: connection refused

### ISSUE THREAD

**Issue by PMDubuc** [prometheus-community/elasticsearch_exporter#809]
I'm running version 1.6.0 of elasticsearch_exporter in a docker on the same host with elasticsearch 7.11.17 also running in a docker and am getting connection errors:

level=error ts=2023-11-06T20:35:58.921739688Z caller=clusterinfo.go:267 msg="failed to get cluster info" err="Get \"http://localhost:9200/\": dial tcp 127.0.0.1:9200: connect: connection refused"
level=error ts=2023-11-06T20:35:58.921783008Z caller=clusterinfo.go:188 msg="failed to retrieve cluster info from ES" err="Get \"http://localhost:9200/\": dial tcp 127.0.0.1:9200: connect: connection refused"

I can run commands on the host like

curl "http://localhost:9200/_cat/indices?v"

and they work.

docker-compose.yml has:

  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.6.0
    restart: always
    ports:
      - 9114:9114

I'm not sure what I'm doing wrong.  Any help would be appreciated.  Thanks.

**Comment by sysadmind** [comment]
Try running curl or wget from the elasticsearc_exporter container. Networking in docker is not the same as on the host. You probably want `http://$elasticsearchContainerName:9200` instead. 

I believe this resource may help explain the networking: https://docs.docker.com/network/network-tutorial-standalone/.
