### ISSUE TITLE
In the latest version 1.7.0, is the code Envar("ES_URI") missing for retrieving the value of es.uri? Currently, when transmitted via ES_URI, it is still bound to the default address.

### ISSUE THREAD

**Issue by karlxu9** [prometheus-community/elasticsearch_exporter#846]
"In the latest version 1.7.0, is the code Envar("ES_URI") missing for retrieving the value of es.uri? Currently, when transmitted via ES_URI, it is still bound to the default address."

**Comment by tanqidi** [comment]
I had the same problem, the ES_URI environment variable didn't work，my version is prometheuscommunity/elasticsearch - exporter: v1.7.0

**Comment by sysadmind** [comment]
the ES_URI env var was removed in 1.4. It is a variable that I am considering bringing back.
