### ISSUE TITLE
1.5.0版本的elasticsearch_exporter连接8.x.x版本的es报错不支持TLS

### ISSUE THREAD

**Issue by Tomcat-kin** [prometheus-community/elasticsearch_exporter#876]
./elasticsearch_exporter --es.all --es.uri elastic:xxxxxxx@localhost:9200
level=info ts=2024-03-26T08:47:45.796922507Z caller=clusterinfo.go:214 msg="triggering initial cluster info call"
level=info ts=2024-03-26T08:47:45.797055326Z caller=clusterinfo.go:183 msg="providing consumers with updated cluster info label"
level=error ts=2024-03-26T08:47:45.797194658Z caller=clusterinfo.go:267 msg="failed to get cluster info" err="Get \"elastic:xxxxxxxx@localhost:9200\": unsupported protocol scheme \"elastic\""
level=error ts=2024-03-26T08:47:45.797235464Z caller=clusterinfo.go:188 msg="failed to retrieve cluster info from ES" err="Get \"elastic:xxxxxxxx@localhost:9200\": unsupported protocol scheme \"elastic\""
level=info ts=2024-03-26T08:47:55.802050458Z caller=main.go:251 msg="initial cluster info call timed out"
level=info ts=2024-03-26T08:47:55.802708853Z caller=tls_config.go:274 msg="Listening on" address=[::]:9114
level=info ts=2024-03-26T08:47:55.802735874Z caller=tls_config.go:277 msg="TLS is disabled." http2=false address=[::]:9114
^Clevel=info ts=2024-03-26T08:47:59.232373898Z caller=clusterinfo.go:231 msg="context cancelled, exiting cluster info trigger loop" err="context canceled"
level=info ts=2024-03-26T08:47:59.23239597Z caller=main.go:295 msg="shutting down"
level=info ts=2024-03-26T08:47:59.232421818Z caller=clusterinfo.go:177 msg="context cancelled, exiting cluster info update loop" err="context canceled"
level=error ts=2024-03-26T08:47:59.232514362Z caller=main.go:289 msg="http server quit" err="http: Server closed"

**Comment by sysadmind** [comment]
I'm not sure what you're asking about as the only info here is log output. 

The URI is incorrect. You are missing a protocol. --es.uri elastic:xxxxxxx@localhost:9200 should be --es.uri https://elastic:xxxxxxx@localhost:9200
