### ISSUE TITLE
Fail to retrieve data from ELK 8.1.1

### ISSUE THREAD

**Issue by TYQ33** [prometheus-community/elasticsearch_exporter#916]
--es.uri http://user:password@x.x.x.x:9200/
For example, if the password is 'H755d8#chi7gf', it would be written like this:http://user/H755d8#chi7gf@x.x.x.x:9200，but still worng.like this below:
"failed to parse es.uri" err="parse \"http://user/H755d8\ ": invalid port l":H755d8\" after host'
How should the password be written if it contains the "#"character? Thanks!

**Comment by sysadmind** [comment]
You need to URL encode the password. In this case replace `#` with `%23`. You can also pass the username and password via the `ES_USERNAME` and `ES_PASSWORD` environment variables instead.
