### ISSUE TITLE
elasticsearch_indices_docs not displaying inside exporters

### ISSUE THREAD

**Issue by aribabuk** [prometheus-community/elasticsearch_exporter#967]
Image used : quay.io/prometheuscommunity/elasticsearch-exporter:latest

            command:
              - /bin/elasticsearch_exporter
              - -es.uri=http://127.0.0.1:9200
              - -es.all=true
              - -es.indices=true
              - -es.timeout=30s
              - -web.listen-address=:9108
              - -web.telemetry-path=/metrics
            ports:
              - containerPort: 9108
            livenessProbe:
              httpGet:
                path: /health
                port: 9108
              initialDelaySeconds: 20
              timeoutSeconds: 3
            readinessProbe:
              httpGet:
                path: /health
                port: 9108
              initialDelaySeconds: 20
              timeoutSeconds: 3

Could you suggest me solution to retrieve details of elasticsearch_indices_docs so that I can see on Prometheus and Grafana

Elasticsearch : 7.17.25
Prometheus : 2.47.0
Exporter : Latest version as per quay.io/prometheuscommunity/elasticsearch-exporter:latest

**Comment by sysadmind** [comment]
When you run the exporter, you can load over http the `/metrics` path to see all of the metrics. You should be able to configure prometheus to scrape the `/metrics` endpoint of the exporter. Maybe I'm not understanding the question. Can you provide more context?

**Comment by aribabuk** [comment]
Hi Joe,

                You can resolve this, after updating to version 1.3.0, issue has been resolved.

Thanks
Aribabu K
